server:
  port: 8888


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: org-117899436@github.com:TeamTobias/config-Repo.git
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKQIBAAKCAgEAy5eigvVupOAfIs2wnrl8bUruDT9iD8fWOPj8gfU4H4q2jw8B
            cpFcIdSkGhifWGw5lx/EajEGyqseFAlcV/NbfrgPEFJSIY/yb3AON51BK31c8YWU
            ZD8wt9zbz8Usn0RStHYw5a84NuGn6EXThAbM9fwAc/mZdZXEsKjlIatwL8sgehS0
            6vA3WCrzMOK+L4xBuWHV3/S43++jXwuk95dT73cicxs36MG2InQVD9H/Z3dJmQbh
            cL6/9F8qGkDX1uinh9V84R63aXBkt1uW1P03wnzGVPPJ1Jp2GTTsyHCJYyUeXEh8
            Fys/j1UWQrJLJMVO7KMCnrZTk5UvNibXM0lePUuOqz4lVWs9yX4mbYKQUPOgFPBj
            iLVmm4QtwUiwWeVzx6ejEt11sn93GAgaN7GzaFG95Pb34DcyKnDspCX/GeRpBfmz
            3Ie0cvcMH/7aLTwma9RsIsji58j1TLje+XuFGoXVEXGn1T/z2dDZxwr0GXjPjlRC
            GzRfB6idPkKjh1LDv1+u1pSrk4q5vsk0PDuMQPm1TEurMOgWXy5IjoFKczwHJ6iT
            olXuQcVMWEFSU0hINrR2FnadGpSdAqlHrfz32rWEVNKaaB0TSV88essATTqJIURV
            xZxHnclJmYQlc5QUkf2ERT9lcNpaqvJfg/4tpcxVa9hNa4jAAji1fWzK2QECAwEA
            AQKCAgB0zV734RUEVGyoi/dbaLEhBs8CHK4GvbCCaR589JGpTuyjsIk1EH4aDqPD
            MQMiOJzlvdzyy4PI/Fk6R5CKCN0iGzjRNVlXVf1Rv6j4cSi1aavMCMX0qWgq4/Pc
            BJQwH4OPcwtkip0mp1msYXsTEM/ABD7CSp2nHzCD5bHnGjM3yEKup3iQHRazZ5i0
            IDHal44RbDbG0ODL4PEKk2Smg1QtW10RSrlNuOzkYVLAC8uKsZ4wxAjMpTL9YSeH
            flIWQs3ymSGXCgdR36B4rXwgX9IAq5Mho+fUKHW+ymVaLW40ylPbv94pcK97bOZj
            h2SjCOvZyT+0jIfwcLNwTuJB00LTwwwvQlgW7MdLgRBlxqAR5DEvqNtTfoyz9v0d
            pu+GwVHv3BgQzNvkw5vJYndL56zHuoUDFr1oZW6ZFCHQgZg4loDF/WrGApEKy7FK
            IE8NVyNqcQkCiP0bfLB/pvwevKxwWYsECC3R/HZnnfC2fRW08en6pCU5Pa15Lk+l
            SQh9H5OiEyZ6FSi/lGhkUga3hjgRwLUpt+LSV9L/n5uf758AVXttVj8sIBhiaihd
            VQDf7eFgVkr3NBKNJuCSJlVTOvw11FjoDKERGYQOvYoQ7e9Eg+dZIESEwZ+HojKN
            GOn7Z4G50+v52ZV+tnlUK3ieA+gkyzJld2O8R7uLMy+bO13f0QKCAQEA9QYXqViu
            mc3cUc9kU4360OVxjxTOOWwDv1jv/yzLzks7V9ACr1h3sTV4M9TayuZd0J8LFGU4
            mVz86YntDniod3vpqHAhwD6FO15TduQ+R7GLOUtO3ZJeO65fcXfTYvllBcifCrfc
            yAPm+uNRl+nWP1JlgxgtPyB7v9CVm3ibh6WyDZ997F9lckdLqXKGGerUzste8AkK
            AAZZnrNGcSDoWUrNx+L509CZlb0hkbs5MXcwndokIH3/3vojn14J/kLE1cWCqlyB
            wnUS1F03NFlQhRWCY1o5sulwsTHG1JSeWMgVYWuyHMVraAwYUXBj/U6bQEo2S4/g
            KUOo60bcWaopZQKCAQEA1LZpF2bAPGE8+bYSm1DnvptRuSIIp93J4EpMEWU7Mhh9
            8fzSVllMbhKxK1DAVf0weXLp9ItgFePzANACwsr4p6DX1ZYXaLli/oTtd6xOfkCk
            2Y3Wf+xtBlsqsmOy3fLtuDz+6WgTJJ3eh6kYc2nJ0IbRM7M5YqX4tPkN4UgIsiUP
            gDSb09/VyuH1HpsTP1pvb/RZL9YS0QNJUtrO4x3MPu8R/KgeGy23F9bmJLSEEyv5
            Cc6IJdX/dU2Cr6/80avzDq+yNQjXbqJuxXnRcNXh4aJZNUbRAxUVRblBS/DAagTl
            3GRNdUYAZQlYK6tgDlZ3upmu78O/2CoIPzCO7gNFbQKCAQEAz3UOGatlggIkFfyU
            BI7FG5P5N101Urca4StrYNHL6eoW373WWCJ+jUMpeDEz4vFz40yV8/nUFz39Qbsv
            RL5yXWBEMQJoAT6uTdsKrjKIbOltaOBTcRUZxkxYsVj0WOuyVlhMGKYeQBfVvP01
            O3uYlFquanXQ8Y8OWBVCZrWSciKgBBrTYoxO95hX/qth0ZXcAw98XZ45olW+EbnW
            3bgwIlJMs36Bao9HStotDxfHUBOLzUtCpWQpfeCqwqe7rFVaFWm6vYW/tCat/7LB
            KAirPVM95+Mf0VUHvm/X2mvPOnqGZ8rorqWU0C7VdDbF4lZo6uEq4YV7FVUdM7/2
            l9CUZQKCAQBbfHTorrXBgmTyVZ/dE0gJD85vXLbyVA7Om8XpuWtjWWtZ184ze0bH
            FN0Ebz+5/CKMKaN8HTHfWGIcmFqHozqdBi2uXFaHISz1oQBtdztvS6hbNYjrDim6
            ER3lCcJVeXVKx1kv1CZfmlKqcEzm3roBKOrzXIMy7YVxeKjCmvO6gvwOvRHEZ8IQ
            92wwlKwLlH7XXPW7AEypfstbimZvAlLlQneu/jOsptXXuALWCJnBkSkUUbL26vpr
            XkH2BDAtkdIBIAn6i2n02IHiB0nQSP1UyTmrE2Ez/S5gBZSS7+Ih9ydRygYSiWAE
            FKfKaHPw1rm6FP1LfBqYA0P2wZDHx7plAoIBAQDdS+b+W6QB3x2vVjDYjga+seUK
            rzbexu5fiyx4SeoHXnQ7vjg0cO5iFwo0z2vGkHlLuyAFM6LrlrIOkqr4desy7r3S
            S/w2SiO74FsEmCbRm0rQBaRMWgLLJaTc5b8tillw482S24B79AAeW0Z0LlmeBU60
            azPJVJ0gRjyJPT94GHqRmbK8HbIieT4Bpd9YRYTzMVb+A3CR2Qfw+THrTRS+qoQw
            0kk32h1eixzYiAu8Np1A0CX+dyBckWO8d/5u9cNkyz6RCoRf1MXQgm6HroVIuB3s
            Kxd7IV8JkyC01gWeUWQx0+BMeIYmcJ9KyhJ+bVVhTNBP1dwuPJd/5WfHKaAs
            -----END RSA PRIVATE KEY-----
          search-paths: basketService,client_Service,client_loginService,couponService,deliveryService,manager_Service,manager_loginService,orderService,pointService,product_cudService,product_readService,recentlyviewedService,review_cudService,review_readService,saler_Service,saler_loginService
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin


management:
  endpoints:
    web:
      exposure:
        include: "*"

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.tobias: DEBUG